name: SlotShop
version: 0.1.0
author: Shantek
main: io.shantek.SlotShop
api-version: 1.17
depend: [Vault]

commands:
  slotshop:
    description: SlotShop plugin command
    usage: /slotshop <subcommand>
    aliases: [ss]
    default: true
    children:
      shantek.slotshop.create:
        description: Create a standard slot shop
        permission: slotshop.create.standard
        default: false
      shantek.slotshop.creategamble:
        description: Create a gamble barrel
        permission: slotshop.create.gamblebarrel
        default: false
      shantek.slotshop.purgegamble:
        description: Reset gamble times for all players
        permission: slotshop.purgegamble
        default: op
      shantek.slotshop.history:
        description: Reset gamble times for all players
        permission: slotshop.history
        default: true
      shantek.slotshop.clear:
        description: Remove old records from purchase history
        permission: slotshop.clear
        default: true
      shantek.slotshop.purgesales:
        description: Remove old records from every player's history
        permission: slotshop.purgesales
        default: op
      shantek.slotshop.addcoowner:
        description: Add a co-owner to a shop
        permission: slotshop.coowner.add
        default: false
      shantek.slotshop.removecoowner:
        description: Remove a co-owner from a shop
        permission: slotshop.coowner.remove
        default: false